[apps]
[[apps.staticweb]]
name = "front"
path = "test"
links = ['front2', 'front3']

[[apps.staticweb]]
name = "front2"
path = "test"

[[apps.staticweb]]
name = "front3"
path = "test"
links = ['front2']