project-id = '1ccf30e1-af0e-4b53-ac94-c1b158e394c0'
server = 'http://localhost:4000/v1'

[apps]
[[apps.docker]]
name = 'back'
image = 'nginx:latest'
allow-origin-from = 'front'

[[apps.docker]]
name = 'front'
image = 'nginx:latest'