project-id = 'e6e19f01-1097-4083-bed4-618fe564a82c'
repository-url = 'https://github.com/RichardDorian/test-pushnpray.git'
server = 'http://localhost:4000/v1/'

[apps]
[[apps.docker]]
name = "nginx"
image = "docker.io/library/nginx:latest"

